### ISSUE TITLE
Judithas issue

### ISSUE THREAD

**Issue by JudithaAga** [luc-girod/forking-workflow-exercise#2]
I want to share my recipes and get feedback.

**Comment by luc-girod** [comment]
You mean, an alternate one? Or do you want to propose some critical changes to the cauliflower recipe?

**Comment by JudithaAga** [comment]
I want to propose a recipe without cauliflower.

**Comment by luc-girod** [comment]
That sounds good!

**Comment by JudithaAga** [comment]
I sent you my new recipe.

**Comment by JudithaAga** [comment]
Thank you!
